### ISSUE TITLE
pins_arduino.h missing RA6M3 HMI-Board

### ISSUE THREAD

**Issue by DansDesigns** [RTduino/RTduino#78]
RT-Thread reports rtduino is missing pins_arduino.h for the RA6M3 HMI-Board.

Is there a fix for this?

```
In file included from C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\core/Print.h:39,
                 from C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\core/Stream.h:38,
                 from C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\libraries\buildin\Wire/Wire.h:40,
                 from ../src/hal_entry.c:14:
C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\core/Printable.h:37:1: error: unknown type name 'class'
   37 | class Print;
      | ^~~~~
C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\core/Printable.h:45:1: error: unknown type name 'class'
   45 | class Printable
      | ^~~~~
C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\core/Printable.h:46:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
   46 | {
      | ^
In file included from C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\core/Stream.h:38,
                 from C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\libraries\buildin\Wire/Wire.h:40,
                 from ../src/hal_entry.c:14:
C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\core/Print.h:46:1: error: unknown type name 'class'
   46 | class Print
      | ^~~~~
C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\core/Print.h:47:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before '{' token
   47 | {
      | ^
In file included from C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\libraries\buildin\Wire/Wire.h:40,
                 from ../src/hal_entry.c:14:
C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\core/Stream.h:61:1: error: unknown type name 'class'
   61 | class Stream : public Print
      | ^~~~~
C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\core/Stream.h:61:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before ':' token
   61 | class Stream : public Print
      |              ^
In file included from C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\libraries\buildin\Wire/Wire.h:41,
                 from ../src/hal_entry.c:14:
C:\RT-ThreadStudio\workspace\hmi-board-factory\packages\RTduino-latest\core/Arduino.h:57:10: fatal error: pins_arduino.h: No such file or directory
   57 | #include "pins_arduino.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [src/subdir.mk:18: src/hal_entry.o] Error 1
make: *** Waiting for unfinished jobs....
"make -j4 all" terminated with exit code 2. Build might be incomplete.

03:21:58 Build Failed. 10 errors, 0 warnings. (took 7s.964ms)
```

**Comment by DansDesigns** [comment]
I couldn't find a solution to the pins_arduino issue so I modified the example ones for the STM32, I am not sure if they work yet as 
I still have issues with 'class' not being recognized in SPI.h, Wire.h, Print.h, Printable.h and Stream.h...

I have attached them to this post so maybe someone else can verify if they work?
[pins_arduino.zip](https://github.com/RTduino/RTduino/files/13037328/pins_arduino.zip)

**Comment by DansDesigns** [comment]
Somehow the 'class' error has fixed itself but now the modified pins_arduino.c is giving the following error:
`../packages/RTduino-latest/core/pins_arduino.c:25:10: error: initializer element is not constant`
this is referencing the first line where D0 is defined but the error applies to all lines..
I did not change the structure of the file just the pins.. here is the contents of the modified pins_arduino.c:
```
/*
 * Copyright (c) 2006-2022, RT-Thread Development Team
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author       Notes
 * 2022-09-20     liYony       first version
 * 19/10/2023     Daniel Miles  updated for RA6M3
 *
 */

#include <Arduino.h>
#include "pins_arduino.h"

/*
 * {Arduino Pin, RT-Thread Pin [, Device Name, Channel]}
 * [] means optional
 * Digital pins must NOT give the device name and channel.
 * Analog pins MUST give the device name and channel(ADC, PWM or DAC).
 * Arduino Pin must keep in sequence.
 */
const pin_map_t pin_map_table[]=
{
    {D0, GET_PIN(P206), "uart1"},      /* Serial-Rx */
    {D1, GET_PIN(P205), "uart1"},       /* Serial-Tx */
    {D2, GET_PIN(P008)},
    {D3, GET_PIN(P506)},
    {D4, GET_PIN(P603), "pwm1", 1},      /* PWM */
    {D5, GET_PIN(P604), "pwm1", 2},     /* PWM */
    {D6, GET_PIN(P605), "pwm1", 3},     /* PWM */
    {D7, GET_PIN(P208)},
    {D8, GET_PIN(P207)},                /* LED_BUILTIN */
    {D9, GET_PIN(P009), "adc1", 5},      /* ADC */
    {D10, GET_PIN(P712), "pwm1", 4},     /* PWM */
    {D11, GET_PIN(P512), "spi1"},       /* SPI-MOSI */
    {D12, GET_PIN(P511), "spi1"},       /* SPI-MISO */
    {D13, GET_PIN(P204),  "spi1"},       /* SPI-SCK */
    {D14, GET_PIN(P203), "i2c1"},        /* I2C-SDA (Wire) */
    {D15, GET_PIN(P202), "i2c1"},        /* I2C-SCL (Wire) */
    {D16, GET_PIN(P209), "led_user1"},       /* user LED 1 */
    {D17, GET_PIN(P210), "led_user2"},       /* user LED 2 */
    {D18, GET_PIN(P005), "btn_user0"},       /* user button 0 */
    {D19, GET_PIN(P006), "btn_user1"},       /* user button 1 */
    {D20, GET_PIN(P007), "btn_user2"},       /* user button 2 */
    {A0, GET_PIN(P00), "adc1", 1},      /* ADC */
    {A1, GET_PIN(P001), "adc1", 2},      /* ADC */
    {A2, GET_PIN(P002), "adc1", 3},      /* ADC */
    {A3, GET_PIN(P003), "adc1", 4},      /* ADC */
    {A4, GET_PIN(P508)},
    {A5, GET_PIN(P014), "adc1", 6},      /* ADC */
    //{A6, RT_NULL, "adc1", RT_ADC_INTERN_CH_VREF},   /* ADC, On-Chip: internal reference voltage */
};

```

**Comment by DansDesigns** [comment]
Any help with this would be greatly appreciated..
This was part of my entry into the RT-Thread Embedded GUI Contest 2023 but I am unable to complete the project due to this error.

**Comment by kurisaW** [comment]
@DansDesigns Hello, currently HMI-Board supports RTduino, you can go to RT-Thread cloning project.Please go to this [link]() to view the RTduino usage documentation and close this issue

**Comment by kurisaW** [comment]
@DansDesigns Since yesterday's pr has not been merged, now you can check the specific use process through the above link, and please feedback to us if you have any questions in the future.

**Comment by mysterywolf** [comment]
Hi, sorry for the late respond. I am too busy, I have merged the PR, please check again.

**Comment by DansDesigns** [comment]
Hi @mysterywolf & @kurisaW, thank you for your replies,

I checked that link again and the readme is now present..
however when starting a new project (or updating an existing one) the errors still persist,
should i manually put the "pins_arduino" files into the correct folders??

Please see attached image for more info

Also i noticed that the I2C1 SCL and SDA are not referenced in the pins_arduino.h however they are already defined in rtconfig.. my hardware is already made to match those pins for I2C1.. is I2C1 usable in rtduino?

![rt-thread_rtduino_error](https://github.com/RTduino/RTduino/assets/72343266/4f7f8e03-7d88-4e33-9acf-a25dce7f0905)

**Comment by kurisaW** [comment]
@DansDesigns 事实上你不应该在软件包中选择RTduino，请清空所有RTduino相关配置，并按照我接下来的步骤完成RTduino的使能：
1.打开RT-Thread studio settings
2.在状态栏选择 'Hardware'
3.Onboard Peripheral Drivers
   --->Compatible with Arduino Ecosystem (RTduino)  (使能该选项)

**Comment by DansDesigns** [comment]
hi @kurisaW,

Thank you for the great tutorial,
It would seem we are using something different as I have no option for "Onboard Peripheral Drivers"...
![rt-thread_rtduino-hardware-issue](https://github.com/RTduino/RTduino/assets/72343266/a0d4f7d8-f245-42ab-aa9f-2fcb9dc29919)

to be honest I am at the end of my rope. I have been struggling with this for over 2 months! 
I am going to throw the board away as it is SO stressful getting a simple arduino layer working.. 
The difficulty i have had with this board has really put me off working on my own projects and I feel like never touching rtthread again..

Thank you for all your help, I hope other are able to get this working.
kind regards

**Comment by kurisaW** [comment]
@DansDesigns A few points need to be made clear to you again:

1. Please download the latest source code of the RT-Thread repository: https://github.com/RT-Thread/rt-thread.git
2. It is recommended that you use RT-Thread's env tool: https://github.com/RT-Thread/env-windows.git

Env to use at the same time please refer to the document center tutorial: https://www.rt-thread.org/document/site/#/development-tools/env/env

Here are some common commands for env:
```bash
scons-j8 // 8 core compiled source code
scons-c // Clear the build
scons --menuconfig // Opens the menu configuration interface, equivalent to settings in Studio
pkgs --update // Update and download the software package
` ` `
3. Directly go to the HMI-Board bsp directory for compilation, or import it to studio

Additional note: For developers, the use of RT-Thread is relatively easy to get started, but the new white need to learn more and draw on the development process of RT-Thread, once you are familiar with the development, I believe you will understand the convenience of RT-Thread

To answer your question above: "I have no option for "Onboard Peripheral Drivers"

This is because the adaptation PR of RTduino was merged yesterday, and you need to synchronize the master branch with git locally. You can refer to my above instructions again for the use configuration after that. If you have any other questions, please contact me!

**Comment by mysterywolf** [comment]
please try use env+vscode
